                     Version      Priority
BH                   "1.84.0-0"   NA           
Biobase              "2.62.0"     NA           
BiocGenerics         "0.48.1"     NA           
BiocIO               "1.12.0"     NA           
BiocManager          "1.30.22"    NA           
BiocNeighbors        "1.20.2"     NA           
BiocParallel         "1.36.0"     NA           
BiocSingular         "1.18.0"     NA           
BiocVersion          "3.18.1"     NA           
Biostrings           "2.70.1"     NA           
Cairo                "1.6-2"      NA           
ComplexHeatmap       "2.18.0"     NA           
DelayedArray         "0.28.0"     NA           
DelayedMatrixStats   "1.24.0"     NA           
FNN                  "1.1.4"      NA           
GenomeInfoDb         "1.38.5"     NA           
GenomeInfoDbData     "1.2.11"     NA           
GenomicAlignments    "1.38.2"     NA           
GenomicRanges        "1.54.1"     NA           
GetoptLong           "1.0.5"      NA           
GlobalOptions        "0.1.2"      NA           
IRanges              "2.36.0"     NA           
MASS                 "7.3-60.0.1" "recommended"
MCMCprecision        "0.4.0"      NA           
Matrix               "1.6-5"      "recommended"
MatrixGenerics       "1.14.0"     NA           
R6                   "2.5.1"      NA           
RColorBrewer         "1.1-3"      NA           
RCurl                "1.98-1.14"  NA           
Rcpp                 "1.0.12"     NA           
RcppAnnoy            "0.0.21"     NA           
RcppArmadillo        "0.12.6.6.1" NA           
RcppEigen            "0.3.3.9.4"  NA           
RcppHNSW             "0.5.0"      NA           
RcppML               "0.3.7"      NA           
RcppProgress         "0.4.2"      NA           
Rhtslib              "2.4.0"      NA           
Rsamtools            "2.18.0"     NA           
Rtsne                "0.17"       NA           
S4Arrays             "1.2.0"      NA           
S4Vectors            "0.40.2"     NA           
ScaledMatrix         "1.10.0"     NA           
SingleCellExperiment "1.24.0"     NA           
SparseArray          "1.2.3"      NA           
SummarizedExperiment "1.32.0"     NA           
WriteXLS             "6.5.0"      NA           
XVector              "0.42.0"     NA           
abind                "1.4-5"      NA           
askpass              "1.2.0"      NA           
base                 "4.3.2"      "base"       
base64enc            "0.1-3"      NA           
beachmat             "2.18.0"     NA           
beeswarm             "0.4.0"      NA           
bitops               "1.0-7"      NA           
bluster              "1.12.0"     NA           
brew                 "1.0-8"      NA           
brio                 "1.1.4"      NA           
bslib                "0.5.1"      NA           
cachem               "1.0.8"      NA           
callr                "3.7.3"      NA           
celda                "1.18.1"     NA           
circlize             "0.4.15"     NA           
cli                  "3.6.2"      NA           
clipr                "0.8.0"      NA           
clue                 "0.3-65"     NA           
cluster              "2.1.6"      "recommended"
codetools            "0.2-19"     "recommended"
colorspace           "2.1-0"      NA           
combinat             "0.0-8"      NA           
commonmark           "1.9.0"      NA           
compiler             "4.3.2"      "base"       
cpp11                "0.4.7"      NA           
crayon               "1.5.2"      NA           
credentials          "2.0.1"      NA           
curl                 "5.2.0"      NA           
data.table           "1.14.10"    NA           
datasets             "4.3.2"      "base"       
dbscan               "1.1-12"     NA           
desc                 "1.4.2"      NA           
devtools             "2.4.5"      NA           
diffobj              "0.3.5"      NA           
digest               "0.6.34"     NA           
doParallel           "1.0.17"     NA           
downlit              "0.4.3"      NA           
dqrng                "0.3.2"      NA           
edgeR                "4.0.9"      NA           
ellipsis             "0.3.2"      NA           
enrichR              "3.2"        NA           
evaluate             "0.22"       NA           
fansi                "1.0.6"      NA           
farver               "2.1.1"      NA           
fastmap              "1.1.1"      NA           
fontawesome          "0.5.2"      NA           
foreach              "1.5.2"      NA           
formatR              "1.14"       NA           
fs                   "1.6.3"      NA           
futile.logger        "1.4.3"      NA           
futile.options       "1.0.1"      NA           
gert                 "1.9.3"      NA           
ggbeeswarm           "0.7.2"      NA           
ggplot2              "3.4.4"      NA           
ggrastr              "1.0.2"      NA           
ggrepel              "0.9.5"      NA           
gh                   "1.4.0"      NA           
gitcreds             "0.1.2"      NA           
glue                 "1.7.0"      NA           
grDevices            "4.3.2"      "base"       
graphics             "4.3.2"      "base"       
grid                 "4.3.2"      "base"       
gridExtra            "2.3"        NA           
gtable               "0.3.4"      NA           
highr                "0.10"       NA           
htmltools            "0.5.7"      NA           
htmlwidgets          "1.6.2"      NA           
httpuv               "1.6.13"     NA           
httr                 "1.4.7"      NA           
httr2                "0.2.3"      NA           
igraph               "1.6.0"      NA           
ini                  "0.3.1"      NA           
irlba                "2.3.5.1"    NA           
isoband              "0.2.7"      NA           
iterators            "1.0.14"     NA           
jquerylib            "0.1.4"      NA           
jsonlite             "1.8.8"      NA           
knitr                "1.44"       NA           
labeling             "0.4.3"      NA           
lambda.r             "1.2.4"      NA           
later                "1.3.2"      NA           
lattice              "0.22-5"     "recommended"
lifecycle            "1.0.4"      NA           
limma                "3.58.1"     NA           
locfit               "1.5-9.8"    NA           
magrittr             "2.0.3"      NA           
matrixStats          "1.2.0"      NA           
memoise              "2.0.1"      NA           
metapod              "1.10.1"     NA           
methods              "4.3.2"      "base"       
mgcv                 "1.9-1"      "recommended"
mime                 "0.12"       NA           
miniUI               "0.1.1.1"    NA           
munsell              "0.5.0"      NA           
nlme                 "3.1-164"    "recommended"
openssl              "2.1.1"      NA           
parallel             "4.3.2"      "base"       
pheatmap             "1.0.12"     NA           
pillar               "1.9.0"      NA           
pkgbuild             "1.4.2"      NA           
pkgconfig            "2.0.3"      NA           
pkgdown              "2.0.7"      NA           
pkgload              "1.3.3"      NA           
plyr                 "1.8.9"      NA           
png                  "0.1-8"      NA           
praise               "1.0.0"      NA           
prettyunits          "1.2.0"      NA           
processx             "3.8.3"      NA           
profvis              "0.3.8"      NA           
promises             "1.2.1"      NA           
ps                   "1.7.6"      NA           
purrr                "1.0.2"      NA           
ragg                 "1.2.7"      NA           
rappdirs             "0.3.3"      NA           
rcmdcheck            "1.4.0"      NA           
rematch2             "2.1.2"      NA           
remotes              "2.4.2.1"    NA           
reshape2             "1.4.4"      NA           
rjson                "0.2.21"     NA           
rlang                "1.1.3"      NA           
rmarkdown            "2.25"       NA           
roxygen2             "7.3.0"      NA           
rprojroot            "2.0.3"      NA           
rstudioapi           "0.15.0"     NA           
rsvd                 "1.0.5"      NA           
rversions            "2.1.2"      NA           
sass                 "0.4.8"      NA           
scales               "1.3.0"      NA           
scater               "1.30.1"     NA           
scran                "1.30.1"     NA           
scuttle              "1.12.0"     NA           
sessioninfo          "1.2.2"      NA           
shape                "1.4.6"      NA           
shiny                "1.7.5.1"    NA           
sitmo                "2.0.2"      NA           
snow                 "0.4-4"      NA           
sourcetools          "0.1.7-1"    NA           
sparseMatrixStats    "1.14.0"     NA           
splines              "4.3.2"      "base"       
statmod              "1.5.0"      NA           
stats                "4.3.2"      "base"       
stats4               "4.3.2"      "base"       
stringi              "1.8.3"      NA           
stringr              "1.5.1"      NA           
sys                  "3.4.2"      NA           
systemfonts          "1.0.5"      NA           
tcltk                "4.3.2"      "base"       
testthat             "3.2.1"      NA           
textshaping          "0.3.7"      NA           
tibble               "3.2.1"      NA           
tinytex              "0.48"       NA           
tools                "4.3.2"      "base"       
urlchecker           "1.0.1"      NA           
usethis              "2.2.2"      NA           
utf8                 "1.2.4"      NA           
utils                "4.3.2"      "base"       
uwot                 "0.1.16"     NA           
vctrs                "0.6.5"      NA           
vipor                "0.4.7"      NA           
viridis              "0.6.4"      NA           
viridisLite          "0.4.2"      NA           
waldo                "0.5.1"      NA           
whisker              "0.4.1"      NA           
withr                "3.0.0"      NA           
xfun                 "0.41"       NA           
xgboost              "1.7.6.1"    NA           
xml2                 "1.3.6"      NA           
xopen                "1.0.0"      NA           
xtable               "1.8-4"      NA           
yaml                 "2.3.8"      NA           
zip                  "2.3.0"      NA           
zlibbioc             "1.48.0"     NA 